# ## NEED TO MOVE THIS OVER TO A TEST
# # Bunch of equations that should work
# validate_formula("~ 0 + group + xyz + (1 | hello)")
# validate_formula("~ group + xyz + (1 | hello)")
# validate_formula("~ 0 + group*xyz + (1 | hello)")
# validate_formula("~ group*xyz")
# validate_formula("~ group*xyz*hello")
# validate_formula("~ group*xyz*hello - xyz:hello")
# validate_formula(~ 0 + group + xyz + (1 | hello))
# validate_formula(~ group + xyz + (1 | hello))
# validate_formula(~ 0 + group*xyz + (1 | hello))
# validate_formula(~ group*xyz)
# validate_formula(~ group*xyz*hello)
# validate_formula(~ group*xyz*hello - xyz:hello)
#
# # Bunch of equations that should fail
# validate_formula("y ~ 0 + group + xyz + (1 | hello)")
# validate_formula(y ~ 0 + group + xyz + (1 | hello))
# validate_formula(0 + group + xyz + (1 | hello))
# validate_formula("0 + group + xyz + (1 | hello)")
# validate_formula(~ 0 + group + xyz + (1 | ))
# validate_formula("~ 0 + group + xyz + (1 | )")
# validate_formula(~ 0 + group + xyz + ( | ))
# validate_formula("~ 0 + group + xyz + (| )")
# validate_formula("~ 0 + group + xyz + (1 || hello)")
# validate_formula("~ 0 + group + xyz + (1 | hello) + (1 | hello)")
# validate_formula("~ 0 + group + xyz + 1 | hello + 1 | hello")
# validate_formula("~ 0 + group + xyz + (1 | hello) + 1 | hello")
# validate_formula("~ 0 + group + xyz + 1 | hello")
# validate_formula(~ 0 + group + xyz + (1 || hello))
# validate_formula(~ 0 + group + xyz + (1 | hello) + (1 | hello))
# validate_formula(~ 0 + group + xyz + 1 | hello + 1 | hello)
# validate_formula(~ 0 + group + xyz + (1 | hello ) + 1 | hello)
# validate_formula(~ 0 + group + xyz + 1 | hello)
# validate_formula("~ 0 + group + xyz + (hello | hello)")
# validate_formula(~ 0 + group + xyz + (hello | hello))
# validate_formula("~ 0 + group + xyz + (1 | hello:group)")
# validate_formula("~ 0 + group + xyz + (1 | hello*group)")
# validate_formula("~ 0 + group + xyz + (1 | hello/group)")
# validate_formula("~ 0 + group + xyz + (1 | hello + group)")
# validate_formula(~ 0 + group + xyz + (1 | hello:group))
# validate_formula(~ 0 + group + xyz + (1 | hello*group))
# validate_formula(~ 0 + group + xyz + (1 | hello/group))
# validate_formula(~ 0 + group + xyz + (1 | hello + group))
# validate_formula("~ group + (1 | group )")
# validate_formula(~ group + (1 | group   ))
