
#' Load DIA data from a MaxQuant Samples Report
#'
#' THIS FUNCTION FOR UAMS INTERNAL USE. This function reads in and parses a UAMS-formatted
#' MaxQuant Samples Report file and creates a DIAlist object containing protein intensity data
#' and annotation data.
#'
#' @param input_file A MaxQuant Samples Report file to be imported.
#' @param sample_IDs Optional: a vector of sample IDs to import. Default is NULL, in which
#'   case all sample IDs (determined from column names in the MaxQuant Samples Report) are
#'   imported.
#'
#' @return A DIAlist containing data and annotation information.
#'
#' @keywords UAMS
#'
#' @export
#'
#' @examples
#' \dontrun{
#' data <- read_DIA_data("path/to/Samples_Report.csv")
#' }
#'
read_DIA_data <- function(input_file = NULL,
                          sample_IDs = NULL) {

  ## IMPORT DATA
  ## the first 10 lines are skipped and last line removed. column 1 (.X)
  ## is renamed "id"
  maxquant_data <- read_maxquant_delim(input_file = input_file)
  rownames(maxquant_data) <- paste0("protein", 1:nrow(maxquant_data))

  # Separate out data columns (which end in .mzML)
  raw_data <- maxquant_data[,stringr::str_detect(colnames(maxquant_data), ".mzML$")]
  # And annotation columns (all other cols)
  raw_annotation <- maxquant_data[,stringr::str_detect(colnames(maxquant_data), ".mzML$", negate = T)]

  ## REPLACE MISSING VALUES WITH ZERO
  ## intensity data is not a numeric data.frame and requires
  ## additional processing numbers are character strings separated
  ## by commas (4,000,000), some cells contain text 'Missing Value'
  ## if the protein does not have detectable expression.
  ## replace 'Missing Value' with zeros, remove comma's, convert
  ## data in each column to numeric values
  raw_data[, ][raw_data[, ] == "Missing Value"] <- "0"

  clean_data <- as.data.frame(apply(raw_data, MARGIN = 2, remove_commas), row.names = rownames(raw_data))
  clean_annot <- parse_protein_data(raw_annotation)

  # For now, check that nrows are equal, but
  # TODO: remove this once the checker does it for us
  stopifnot(nrow(clean_data) == nrow(clean_annot))
  stopifnot(rownames(clean_data) == rownames(clean_annot))

  num_samples   <- ncol(clean_data)
  num_extracted <- nrow(clean_data)

  cli::cli_inform(c("Intensity data for {.val {num_extracted}} DIA protein entries and {.val {num_samples}} samples extracted"))

  ## return a list of data.frame containing the extracted quality
  ## filtered intensity data, corresponding extracted annotation,
  ## stats, and input parameters
  out <- list(
    data = clean_data,
    annotation = clean_annot,
    metadata = NULL,
    design = NULL,
    eBayes_fit = NULL,
    results = NULL,
    tags = NULL
  )

  validate_DIAlist(new_DIAlist(out))
}



#' Import MaxQuant data
#'
#' THIS FUNCTION FOR UAMS INTERNAL USE. This is a subfunction of \code{\link{read_DIA_data}},
#' used to read in tabular data. This function is not meant to be called by users.
#'
#' @inheritParams read_DIA_data
#'
#' @return A data frame, where each row is a (raw) protein, the first
#'        few columns are annotation data, and the last columns are the individual
#'        sample intensities (as character vectors).
#'
#' @keywords UAMS, internal
#'
read_maxquant_delim <-function(input_file) {
  ## check that the file is a csv, tsv, or text file
  filext <- stringr::str_to_lower(file_extension(input_file))
  if (filext %notin% c("csv","txt","tsv")) {
    cli::cli_abort(c("Problem with input file",
                     "x" = "Input file must end in {.file .csv}, {.file .tsv}, or {.file .txt}"))
  }

  ## check that file exists
  if (!file.exists(input_file)) {
    cli::cli_abort(c("Cannot find file.",
                     "x" = "{.file {input_file}} does not exist",
                     "i" = "Did you specify the filepath correctly?"))
  }

  if(filext=="txt" | filext=="tsv"){ sep="\t" }
  if(filext=="csv"){ sep=","}


  ## sample report generated by scaffold DIA is imported as data.frame.
  ## Sample Reports generated by Scaffold DIA contain meta data in the
  ## first 10 lines, and text in the last row to mark the end of the file.
  ## Thus, when reading in the file the first 10 lines are skipped and the
  ## last row is removed. column name of column 1 (X. on import) is changed to id
  ## column 1 must be changed to "id" to allow extraction and other processing.
  ## Note: column names of the input file are defined according to R syntax rules.
  ## special characters, spaces, are converted to periods.
  data <- utils::read.csv(file = input_file, sep = sep, stringsAsFactors = FALSE,
                          header = TRUE, check.names = TRUE, skip = 10)

  if (data[nrow(data),1] == "END OF FILE") {
    data <- data[-nrow(data),]
  }

  ## name of column 1 is changed to 'id'
  if (colnames(data)[1] == "X.") {colnames(data)[1] <- "id"}

  data
}


#' Parse protein data
#'
#' THIS FUNCTION FOR UAMS INTERNAL USE. This is a subfunction of \code{\link{read_DIA_data}},
#' used to parse protein annotation data out of the data imported from a MaxQuant file.
#' This function is not meant to be called by users.
#'
#'
#' @param annotation_data Annotation data from which to parse protein data.
#' @return A data frame of cleaned annotation data.
#'
#'
#' @keywords UAMS, internal
#'
parse_protein_data <- function(annotation_data) {

  ## extract gene name, gene symbol, and uniprot id info. from the Fasta.header
  ## append to qfilterData add unique protein ID (proKey = uniprot_GN_id
  annotation_data$Accession.Number <- gsub("(.+?)(\\ .*)","\\1", stringr::str_extract(annotation_data$Protein.Name,"(?<=\\|)[^\\|]+(?=\\ )"))
  annotation_data$UniprotID    <- stringr::str_extract(annotation_data$Protein.Name, "(?<=\\|)[^\\|]+(?=\\|)")
  annotation_data$Gene_name    <- stringr::str_extract(annotation_data$Protein.Name, "(?<=GN\\=)[^\\|]+(?= PE\\=)")
  annotation_data$Description  <- stringr::str_extract(annotation_data$Protein.Name, "(?<= )[^\\|]+(?= OS\\=)")

  annotColums <- diaAnnotationColums
  annotColums <- c(annotColums, "UniprotID", "Gene_name","Description")
  #rownames(annotation_data) <- paste(annotation_data$UniprotID, annotation_data$Gene_name, annotation_data$id, sep="_")

  annotation_data[, unique(c(annotColums, "UniprotID", "Gene_name","Description"))]
}


